# Generated by Django 5.2.17 on 2026-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantidentificationhistory',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Confidence percentage e.g. 96.5'),
        ),
        migrations.AlterField(
            model_name='plantidentificationhistory',
            name='identified_name',
            field=models.CharField(blank=True, default='Pending Identification', max_length=200),
        ),
    ]
