# Generated by Django 5.2.17 on 2026-08-12 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('plant_image', models.ImageField(blank=True, null=True, upload_to='saved_plants/')),
                ('watering_frequency', models.TextField(blank=True, help_text='e.g. Every 7 days or when top soil dries')),
                ('sunlight_requirement', models.TextField(blank=True, help_text='e.g. Bright indirect sunlight')),
                ('soil_type', models.TextField(blank=True, help_text='e.g. Well-draining potting mix with perlite')),
                ('fertilizer_info', models.TextField(blank=True, help_text='e.g. Liquid fertilizer every 4 weeks in summer')),
                ('confidence_score', models.FloatField(blank=True, help_text='Score if saved from identification', null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal care notes or reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
